apiVersion: v1
kind: Service
metadata:
  name: cmsservice
  namespace: typo3-playground
spec:
  selector:
    app: typo3cms
  type: NodePort
  ports:
  - nodePort: 31001
    port: 80
    targetPort: 80
    protocol: TCP
